In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[-2.3061e-24,  4.5556e-41, -2.3061e-24],
        [ 4.5556e-41,  4.5708e+27,  1.6900e+28],
        [ 6.7602e+28,  2.7041e+29,  1.6944e+28],
        [ 2.7165e+29,  1.5322e+10,  1.0795e+30],
        [ 6.1205e+10,  1.8812e+31,  1.3322e-40]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9993, 0.3410, 0.0783],
        [0.8554, 0.8317, 0.2248],
        [0.2520, 0.9307, 0.1003],
        [0.4165, 0.9706, 0.3934],
        [0.1462, 0.9109, 0.2699]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.3961, -1.4967, -1.3807],
        [-1.1198, -1.1257, -0.0548],
        [ 0.7925,  0.4900,  0.4562],
        [-1.4620, -0.4053, -0.9589],
        [-0.5776,  1.4032,  0.4238]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

In [9]:
torch.cuda.is_available()

False

In [10]:
torch.backends.cudnn.enabled

True

In [1]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

NameError: name 'torch' is not defined